# Generated by Django 3.2.8 on 2021-10-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField()),
                ('url_flipkart', models.URLField(blank=True, null=True)),
                ('url_amazon', models.URLField(blank=True, null=True)),
                ('price_flipkart_xmlpath', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amazon_xmlpath', models.CharField(blank=True, max_length=1000, null=True)),
                ('comapare_flipkart_price', models.CharField(blank=True, max_length=20, null=True)),
                ('compare_amazon_price', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flipkart_image', models.ImageField(blank=True, default='default-product.png', upload_to='flipkart')),
                ('amazone_image', models.ImageField(blank=True, default='default-product.png', upload_to='amazone')),
                ('comapare_flipkart_price', models.FloatField(blank=True, null=True)),
                ('compare_amazon_price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('comapare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ('-created_on',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
