# Generated by Django 3.2.8 on 2021-10-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadd',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
