# Generated by Django 3.2.8 on 2021-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productadd_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadd',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
