# Generated by Django 3.2.8 on 2021-11-05 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadd',
            name='our_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productadd',
            name='our_product_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='our_product'),
            preserve_default=False,
        ),
    ]
