# Generated by Django 3.2.6 on 2022-01-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220106_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadd',
            name='count',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
