# Generated by Django 3.2.6 on 2022-01-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productadd_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
