# Generated by Django 3.2.8 on 2021-11-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0003_alter_cart_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
