# Generated by Django 3.2.8 on 2021-10-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
